### ISSUE TITLE
We need to create a update script for submodules 

### ISSUE THREAD

**Issue by vfonsecapv** [cloudfoundry-community/logsearch-for-cloudfoundry#100]
#!/bin/bash

if [ "$1" == "--help" ]; then
  echo "USAGE: $0"
  echo "    This command takes no arguments."
  echo ""
  echo "This script does a git submodule update on all submodules"
  exit 0
fi

function has_upstream() {
  git rev-parse @{u} > /dev/null 2>&1
}

set -x -e

scripts_dir="$(cd $(dirname $0) && pwd)"
if [ -d "$(dirname "$scripts_dir")/.git" ] ; then
  "$scripts_dir"/install-git-hooks
fi

has_upstream && git pull

if [[ "$(git --version | grep 'version 1.7')x" != "x" ]]; then
  git submodule foreach --recursive git submodule sync && git submodule update --init --recursive
else
  git submodule sync --recursive && git submodule foreach --recursive git submodule sync  && git submodule update --init --recursive
fi

**Comment by Infra-Red** [comment]
@axelaris 
Update script was introduced in next [PR](https://github.com/cloudfoundry-community/logsearch-for-cloudfoundry/pull/102). I think we can close this issue.

**Comment by axelaris** [comment]
Agree. Closing down the issue.
