### ISSUE TITLE
Give collaborators commit access

### ISSUE THREAD

**Issue by mrdavidlaing** [cloudfoundry-community/logsearch-for-cloudfoundry#15]
I prefer a pull request based workflow where the PR originates in the same repo as the target, since then feedback can be given by committing changes to the PR branch

@mention me if you want commit access, and have signed the CLA

**Comment by mrdavidlaing** [comment]
@drnic, @rkoster, @longnguyen11288, @malston - I'm giving you commit access to this repo.

Please leave commiting to master to me; but feel free to commit to branches and raise a PR to get those changes merged into master

**Comment by mrdavidlaing** [comment]
Welcome @simonjohansson!

**Comment by simonjohansson** [comment]
Danke!

**Comment by mrdavidlaing** [comment]
Simon,

Have you accepted the invite yet?  Github says it is pending, and Gitter
won't let me add you to the chatroom until you are a member of the
logsearch org

On 1 April 2015 at 10:56, Simon Johansson <notifications@github.com> wrote:

> Danke!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/logsearch/logsearch-for-cloudfoundry/issues/15#issuecomment-88421343>
> .
>



-- 
David Laing
logsearch.io - build your own open source cloud logging cluster
http://davidlaing.com

**Comment by simonjohansson** [comment]
@mrdavidlaing just accepted.

**Comment by mrdavidlaing** [comment]
Cool - Gitter has let me invite you - see https://gitter.im/logsearch

On 1 April 2015 at 11:19, Simon Johansson <notifications@github.com> wrote:

> @mrdavidlaing <https://github.com/mrdavidlaing> just accepted.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/logsearch/logsearch-for-cloudfoundry/issues/15#issuecomment-88427974>
> .
>



-- 
David Laing
logsearch.io - build your own open source cloud logging cluster
http://davidlaing.com

**Comment by mrdavidlaing** [comment]
@shinji62, I've just invited you to join the  logsearch-for-cloudfoundry.

Please accept the invitation so you can join us in the https://gitter.im/logsearch chat.
