### ISSUE TITLE
Add predefined index patterns in Kibana

### ISSUE THREAD

**Issue by hannayurkevich** [cloudfoundry-community/logsearch-for-cloudfoundry#161]
Investigate if it is possible to load predefined index patterns in Kibana when setting up ELK.
(it looks like this requires edit of .kibana index)
If it is possible - create predefined index patterns and make them be created as part of ELK setup.

Useful doc: https://discuss.elastic.co/t/kibana-4-unattended-configuration-of-default-index-pattern/1737/5

**Comment by jmcarp** [comment]
If I'm understanding this issue correctly, those index patterns live in https://github.com/cloudfoundry-community/logsearch-for-cloudfoundry/tree/master/src/logsearch-config/src/kibana4-dashboards/index-pattern. They're dumped to `.json.erb` files in https://github.com/cloudfoundry-community/logsearch-for-cloudfoundry/blob/7897021603f2a10fe7b36d636fd683a6039c8f20/src/logsearch-config/src/kibana4-dashboards/fetch_dashboards.rb#L72-L73. We're using the `upload-kibana-dashboards` errand to upload those and other kibana configuration files, so if that gets merged, this should be satisfied.

**Comment by hannayurkevich** [comment]
https://github.com/cloudfoundry-community/logsearch-for-cloudfoundry/pull/188
