### ISSUE TITLE
Review stale branches

### ISSUE THREAD

**Issue by axelaris** [cloudfoundry-community/logsearch-for-cloudfoundry#174]
Please review stale branches and see if they contain anything helpful for current state.
@hannayurkevich: [allow_access_to_cf](https://github.com/cloudfoundry-community/logsearch-for-cloudfoundry/tree/allow_access_to_cf)
@Infra-Red: [push-kibana-issues](https://github.com/cloudfoundry-community/logsearch-for-cloudfoundry/tree/push-kibana-issues), [upgrade_for_elasticsearch2](https://github.com/cloudfoundry-community/logsearch-for-cloudfoundry/tree/upgrade_for_elasticsearch2)

**Comment by Infra-Red** [comment]
@axelaris both branches [push-kibana-issues](https://github.com/cloudfoundry-community/logsearch-for-cloudfoundry/tree/push-kibana-issues), [upgrade_for_elasticsearch2](https://github.com/cloudfoundry-community/logsearch-for-cloudfoundry/tree/upgrade_for_elasticsearch2) are outdated, I will delete these branches.

**Comment by axelaris** [comment]
@Infra-Red Ok

**Comment by hannayurkevich** [comment]
Branch [allow_access_to_cf](https://github.com/cloudfoundry-community/logsearch-for-cloudfoundry/tree/allow_access_to_cfl) is outdated, so I deleted it.
