### ISSUE TITLE
Add missing step for yaml tests in install-dependencies

### ISSUE THREAD

**Issue by hannayurkevich** [cloudfoundry-community/logsearch-for-cloudfoundry#180]
I get the following when running tests on my test env:
`===> Validating YAML data ...
 yaml-lint $(find ../.. -path ../../src -prune -o -name '*.yml' -print)
sh: 1: yaml-lint: not found
rake aborted!
Command failed with status (127): [ yaml-lint $(find ../.. -path ../../src -p...]
/home/ubuntu/deployments/elk/logsearch-for-cloudfoundry/src/logsearch-config/Rakefile:44:in block in <top (required)>
Tasks: TOP => default => yaml
(See full trace by running task with --trace)`

It looks like `bundle install` step is missing. Please add it to install-dependencies.

**Comment by Infra-Red** [comment]
Fixed https://github.com/cloudfoundry-community/logsearch-for-cloudfoundry/commit/c16fddc1799331baf52cc2bcbd0dbb9cbdb084dc
