### ISSUE TITLE
Test Kibana authentication when deploying Kibana as an instance

### ISSUE THREAD

**Issue by hannayurkevich** [cloudfoundry-community/logsearch-for-cloudfoundry#189]
It looks like we need to have a job in manifest:

https://github.com/cloudfoundry-community/logsearch-for-cloudfoundry/blob/develop/templates/logsearch-for-cf.example-with-uaa-auth.yml#L75

**Comment by hannayurkevich** [comment]
Make sure that it is possible to install authentication plugin to both cf-kibana and standalone Kibana instance.

**Comment by Infra-Red** [comment]
Auth plugin works with standalone Kibana instance deployed with BOSH. Also added missing env variables in template 43e8ae58a09b87023cbb30776f797b531c719a43.
