### ISSUE TITLE
Add to https://bosh.io/releases

### ISSUE THREAD

**Issue by jmcarp** [cloudfoundry-community/logsearch-for-cloudfoundry#195]
It would be useful if this could be added to https://bosh.io/releases. Related, it would be helpful to resume regular releases with a changelog so that users like me can understand when and how to upgrade. One more question: do you recommend using the `master` or `develop` branch? When is `develop` merged into `master`?

**Comment by jmcarp** [comment]
Quick question @hannayurkevich: for now, would you recommend using `develop` or `master`?

**Comment by Infra-Red** [comment]
@jmcarp I would recommend to use `release-candidate` branch, we are testing every commit to develop with our concourse pipeline, so if commit from develop has passed all tasks it will be automatically merged to `release-candidate` branch.

**Comment by jmcarp** [comment]
@Infra-Red: it looks like `release-candidate` hasn't updated since October. Is it still getting updated from CI?

**Comment by axelaris** [comment]
added to bosh.io
