### ISSUE TITLE
What version of logsearch-boshrelease for this? cluster_monitor not running after update

### ISSUE THREAD

**Issue by tomsherrod** [cloudfoundry-community/logsearch-for-cloudfoundry#200]
I've got a working logsearch-boshrelease, 204.0.0. 
When I try to deploy with logsearch-for-cloudfoundry, the cluster_monitor update fails(after a long time) with parser job failure. Parser logs indicates a Redis connection problem, when redis isn't even running on at 127.0.0.1.
Not getting much from there, checked the parser/config directory before running the re-deploy. The directory contains logstash.conf, deployment_lookup.yml, filters_override.conf, filters_post.conf, filters_pre.conf and input_and_output.conf. After the failed deploy, no deployment_lookup.yml and a LOT less filtering in the conf files.

Pointers in debugging the issue?
Should I be using a different version of the logsearch-boshrelease?

**Comment by Infra-Red** [comment]
@tomsherrod I would recommend to use the version number 203.0.0 of logsearch-boshrelease. 204.0.0 version was reverted in commit https://github.com/logsearch/logsearch-boshrelease/commit/ae5fda583a4da88ca947f4b3ed11a5b8136eba1f, so I would not use this release.

**Comment by tomsherrod** [comment]
@Infra-Red Thanks for the pointer.
cluster_monitor update still fails.
Found a clearer problem /var/vcap/sys/log/monit:
parser.err.log
::::::::::::::
------------ STARTING parser_ctl at Tue Oct  4 19:55:03 UTC 2016 --------------
cp: cannot stat ‘/var/vcap/jobs/logsearch-for-cloudfoundry-filters/config/deployment_lookup.yml’: No such file or directory

No /var/vcap/jobs/logsearch-for-cloudfoundry-filters exists on the cluster_monitor instance.
I'm using the stub.logsearch-for-cloudfoundry.yml to generate the manifest. Looks very different from the logsearch-for-cf.example-with-uaa-auth.yml.  
I don't wish to have any auth.

**Comment by hannayurkevich** [comment]
Hi @tomsherrod,

I've made a [fix](https://github.com/cloudfoundry-community/logsearch-for-cloudfoundry/commit/3c25325d8351bee714c9af7484dae44d1249a447) which adds missing deployment* properties to logsearch-for-cf.example-with-uaa-auth.yml template.

I'm not sure if it fixes the problem you have. Please try to use the latest changes anyway.

Also it would be really useful if you share your deployment manifest to understand what can be the cause of the errors you get.

Thanks in advance.

**Comment by tomsherrod** [comment]
Hi @hannayurkevich,


I used the logsearch-for-cf.example-with-uaa-auth.yml template, removing the uaa part to achieve success! Well, I now have dashboards with some data. Now on to debugging what data is not getting where. Awesome. Thank you.

Here are the yml files. https://gist.github.com/tomsherrod/5265a44322183aa88f646d291c52f975
Anything you see odd in yml, I welcome pointers.

**Comment by hannayurkevich** [comment]
Hi @tomsherrod, glad to hear that the fix helped. Do you still have some issues?

**Comment by tomsherrod** [comment]
Specific to this issue, no. I'm running into some other things. Will need to nail specifics to give us something to work with. 
A big thank you.
