### ISSUE TITLE
Make data uploaded as Kibana objects configurable

### ISSUE THREAD

**Issue by hannayurkevich** [cloudfoundry-community/logsearch-for-cloudfoundry#201]
[This line](https://github.com/cloudfoundry-community/logsearch-for-cloudfoundry/blob/develop/jobs/upload-kibana-objects/templates/bin/run#L6) should be reworked to use property instead of a hardcoded path. The property should accept a list of values with default value set to the hardcoded path used at the moment - so that user can choose whether to upload the default objects and at the same time have possibility to upload custom objects.

**NOTE:** Make sure to update documentation (1) Jobs section / logsearch-for-cloudfoundry-filters job - Deployment column; 2) Customization - describe Kibana saved objects customization)

**Comment by Infra-Red** [comment]
Property added in https://github.com/cloudfoundry-community/logsearch-for-cloudfoundry/commit/763cf29c8e6813727ced5dc058f3486c9e7d4dc9.

**Comment by hannayurkevich** [comment]
Also updated documentation.
