### ISSUE TITLE
Please complete the deployment sections

### ISSUE THREAD

**Issue by middleagedman** [cloudfoundry-community/logsearch-for-cloudfoundry#208]
I really need this critical piece of information in order to combine it with the logsearch-boshrelease

**Comment by Infra-Red** [comment]
Hi @middleagedman !
I added document about deployment process https://github.com/cloudfoundry-community/logsearch-for-cloudfoundry/blob/develop/docs/deployment.md.
Feel free to open issues in case of problems during deployment.
Thanks!

**Comment by middleagedman** [comment]
Fantastic!  Thank you very much.  Doing a deployment trial tomorrow :)

**Comment by middleagedman** [comment]
Last thing I'm missing is this
"Deploy Kibana as CloudFoundry application"

Reason is I couldn't get the uaac to work because the create-uaa-client errand creates the tokens expecting a redirect to logs.example.cf.com for the kibana site, but since it's a bosh vm it only has an IP and not a name (since it's not an app).  So I figured I would try the above step.

Is it as simple as regenerating the manifest using the logstash-boshrelease.yml + a copy of an edited stub.logsearch-for-cloudfoundry.yml (since this is the only file that had the cf-kibana errand).

Thanks!

**Comment by Infra-Red** [comment]
Hi @middleagedman !
I fixed `redirect_uri` in create-uaa-errand https://github.com/cloudfoundry-community/logsearch-for-cloudfoundry/commit/c624dce7890a8901898ae51a91064622ae0bbe41, now you can specify your Kibana domain with property `create-uaa-client.elk_domain`.

**Comment by middleagedman** [comment]
Great thanks!  I had just figured out how to manually fix it on Friday and you beat me to the commit!
