### ISSUE TITLE
Customisation doc misleading

### ISSUE THREAD

**Issue by saliceti** [cloudfoundry-community/logsearch-for-cloudfoundry#212]
The [parsing rules](https://github.com/cloudfoundry-community/logsearch-for-cloudfoundry/blob/develop/docs/customization.md#parsing-rules) section in the customisation doc says the rules can be added within a block.

I have tried it but it didn't work for me. And I don't see how it would work, as the [the code that uses that property](https://github.com/cloudfoundry-community/logsearch-boshrelease/blob/develop/jobs/parser/templates/bin/parser_ctl#L57-L65) only allows either one string, or an array of paths.

**Comment by hannayurkevich** [comment]
This should be fixed in conjunction with https://github.com/cloudfoundry-community/logsearch-for-cloudfoundry/issues/182.

**Comment by hannayurkevich** [comment]
Fixed in https://github.com/cloudfoundry-community/logsearch-for-cloudfoundry/commit/631fe0ad2ce69b5daa80dfd5e442bbb72fb38247#diff-4b575591f248fd10193e79c37560ce93.
