### ISSUE TITLE
Document breaking changes and upgrade paths

### ISSUE THREAD

**Issue by jmcarp** [cloudfoundry-community/logsearch-for-cloudfoundry#225]
To prevent breaking changes from affecting downstream users, it would be helpful for this project to adopt semantic versioning and keep a log of breaking changes. There have been a few breaking changes related to renaming jobs and templates in the last month, and we've had to page through commits looking for the relevant changes to resolve. Ideally, any breaking change would be accompanied by an entry in the changelog describing how to upgrade.

Related to #195. cc @cnelson

**Comment by axelaris** [comment]
Fixed by https://github.com/cloudfoundry-community/logsearch-for-cloudfoundry/commit/1245e7453a0771462228c77cc7ad7207d21edd9e
