### ISSUE TITLE
deployment_dictionary parser issue

### ISSUE THREAD

**Issue by middleagedman** [cloudfoundry-community/logsearch-for-cloudfoundry#228]
It looks like the fields for deployment dictionary are not compatible with how logsearch-boshrelease runs the parser_ctl.  I.e.
      deployment_dictionary:
      - /var/vcap/packages/logsearch-config/deployment_lookup.yml
      - /var/vcap/jobs/parser-config-lfc/config/deployment_lookup.yml

Gets passed to logsearch-boshrelease/jobs/parser/templates/bin/parser_ctl (or /var/vcap/jobs/parser/bin/parser_ctl)

And this line breaks trying to copy the files into config.
    cp "<%= p("logstash_parser.deployment_dictionary") %>" "${JOB_DIR}/config"

as it becomes

cp ""["/var/vcap/packages/logsearch-config/deployment_lookup.yml"]", "[/var/vcap/jobs/parser-config-lfc/config/deployment_lookup.yml"]"" /var/vcap/jobs/parser/config

**Comment by hannayurkevich** [comment]
Hi @middleagedman ,

Which version of logsearch-boshrelease are you using? Please use `develop` version of `logsearch-boshrelease` if you are using `develop` version of Logsearch-for-cloudfoundry (see [versions compatibility](https://github.com/cloudfoundry-community/logsearch-for-cloudfoundry/blob/develop/docs/versions.md)).

Here is the piece of `parser_ctl` script for deployment dictionary copying - https://github.com/cloudfoundry-community/logsearch-boshrelease/blob/develop/jobs/parser/templates/bin/parser_ctl#L51-L53. So it should work fine with the config you mentioned if you use `develop`.

Let me know if you still have an issue with this.

**Comment by middleagedman** [comment]
Ah thanks.. yea I had been using 203 due to weird 204 commits.
