### ISSUE TITLE
/jobs/elasticsearch-config-lfc/spec log naming is incorrect

### ISSUE THREAD

**Issue by middleagedman** [cloudfoundry-community/logsearch-for-cloudfoundry#229]
I had to fix this line today in order to deploy the release

index 77e3dda..73d9446 100644
--- a/jobs/elasticsearch-config-lfc/spec
+++ b/jobs/elasticsearch-config-lfc/spec
@@ -10,4 +10,4 @@ properties:
       Name prefix of your log indices that can uniquely distinguish them among other ES indices if apply pattern '*' to it, e.g. 'logs-*'. 
       It is used in the index templates predefined in the job to specify index pattern.
       Make sure the prefix matches `logstash_parser.elasticsearch.index` property set for your parser.
-    default: "logs-"
+    default: "logstash-%{+YYYY.MM.dd}"

**Comment by hannayurkevich** [comment]
Right, I'll fix the spec.

Thanks!

**Comment by hannayurkevich** [comment]
Fixed in https://github.com/cloudfoundry-community/logsearch-for-cloudfoundry/commit/dcd2b59fae9811e55df7d90bdf8e9bf3d5e51bb5.
