### ISSUE TITLE
Wrong link to logsearch-boshrelease in docs/intro.md

### ISSUE THREAD

**Issue by antonsoroko** [cloudfoundry-community/logsearch-for-cloudfoundry#236]
Wrong link to logsearch-boshrelease in docs/intro.md:
https://github.com/logsearch/logsearch-boshrelease

**Comment by Infra-Red** [comment]
Thanks @antonsoroko . Fixed with https://github.com/cloudfoundry-community/logsearch-for-cloudfoundry/commit/32c7f2245f7b363dc8d0cd80c70704d57209f85e.
