### ISSUE TITLE
cf-routing for ls-router

### ISSUE THREAD

**Issue by comxtohr** [cloudfoundry-community/logsearch-for-cloudfoundry#238]
Original `logsearch-boshrelease` needs to set a domain name for `ls-router` manually.
Is it a good idea to add a `route_registrar` template(`cf-routing` release) to job `ls-router`?
It can assign a domain name for `ls-router` automatically.

**Comment by Infra-Red** [comment]
Added in https://github.com/cloudfoundry-community/logsearch-for-cloudfoundry/commit/32e1e4251533bccce284dad6420c88508c0b0406.
