### ISSUE TITLE
Use latest firehose-to-syslog

### ISSUE THREAD

**Issue by geofffranks** [cloudfoundry-community/logsearch-for-cloudfoundry#241]
There are a number of updates + fixes to firehose-to-syslog that would lead to a better troubleshooting experience (prints errors when connecting to CF instead of nil-pointer panics). Would be great if we could update to the latest version in this release.

**Comment by Infra-Red** [comment]
Firehose-to-syslog updated to v3 in [v204.0.0](https://github.com/cloudfoundry-community/logsearch-for-cloudfoundry/releases/tag/v204.0.0) release.
