### ISSUE TITLE
Not explained correct corresponding version of logsearch-boshrelease?

### ISSUE THREAD

**Issue by k-tooriyama** [cloudfoundry-community/logsearch-for-cloudfoundry#243]
This is a document bug? 

In following page's Dependencies & compatibility matrix, the corresponding version of logsearch-boshrelease is "develop" and the link leads us to the develop branch of "logsearch"/logsearch-boshrelease.
https://github.com/cloudfoundry-community/logsearch-for-cloudfoundry/blob/v202.0.0/docs/versions.md
I'm guessing "cloudfoundry-community"/logsearch-boshrelease should be linked, because logsearch/logsearch-boshrelease is "No longer maintained."

Even if it's correct, is logsearch-for-cloudfoundry v202 really corresponding to logsearch-boshrelease's "develop" branch? As the branch developed day by day,  I wonder if their compatibility might being lost.

I'm trying to deploy logsearch and logsearch4cf, so I'd like to correct compatibility matrix. I'd appreciate it if you tell me the answer :-)

**Comment by Infra-Red** [comment]
I've included a Compatible Releases section in release notes, please use the versions mentioned in this section.

**Comment by k-tooriyama** [comment]
Thanks a lot! I've gotten information I should know.
I believe a compatible release section helps those who want to use ls4cf. It's very nice.
