### ISSUE TITLE
Logs stop coming in, errors in Ingestor & Queue VM

### ISSUE THREAD

**Issue by moizkhan2712** [cloudfoundry-community/logsearch-for-cloudfoundry#247]
Hi,

We've deployed Logsearch + Logsearch for CF on vSphere with 4 data nodes. While it runs well for several hours, the logs stop appearing. Upon investigating, we find the following in the Ingestor VM's log file (ingestor_syslog.stdout.log):

```
[2017-04-24T05:08:37,371][ERROR][l.pipeline               ] A plugin had an unrecoverable error. Will restart this plugin.
  Plugin: <LogStash::Inputs::Tcp add_field=>{"type"=>"syslog"}, host=>"0.0.0.0", port=>5514, id=>"aee79dea2f19fbfecae270ce3de2bec5d845c116-1", enable_metric=>true, codec=><LogStash::Codecs::Line id=>"line_80eca8c1-f71f-4180-9554-f13e3870e5c9", enable_metric=>true, charset=>"UTF-8", delimiter=>"\n">, data_timeout=>-1, mode=>"server", proxy_protocol=>false, ssl_enable=>false, ssl_verify=>true, ssl_key_passphrase=><password>>
  Error: closed stream

[2017-04-24T05:08:38,371][ERROR][l.pipeline               ] A plugin had an unrecoverable error. Will restart this plugin.
  Plugin: <LogStash::Inputs::Tcp add_field=>{"type"=>"syslog"}, host=>"0.0.0.0", port=>5514, id=>"aee79dea2f19fbfecae270ce3de2bec5d845c116-1", enable_metric=>true, codec=><LogStash::Codecs::Line id=>"line_80eca8c1-f71f-4180-9554-f13e3870e5c9", enable_metric=>true, charset=>"UTF-8", delimiter=>"\n">, data_timeout=>-1, mode=>"server", proxy_protocol=>false, ssl_enable=>false, ssl_verify=>true, ssl_key_passphrase=><password>>
  Error: closed stream

```
Also, the Queue (Redis) VM has the following in queue.log:

```
11592:M 24 Apr 05:10:35.999 * Starting automatic rewriting of AOF on 145% growth
11592:M 24 Apr 05:10:35.999 # Error opening /setting AOF rewrite IPC pipes: Too many open files
```

This error is usually resolved by doing a monit restart on the ingestor VM. However, during that time, there are several logs file lost and we can't do that regularly on a sensitive system. Attached is our manifest for the Logsearch+CF deployment. Any specific reason this could be happening?

Thanks & Regrds,
Moiz Khan

[logsearch+cf.txt](https://github.com/cloudfoundry-community/logsearch-for-cloudfoundry/files/950504/logsearch.cf.txt)

**Comment by BernhardDenner** [comment]
+1 facing the same issue

**Comment by moizkhan2712** [comment]
I'd created a pull request on [logsearch-boshrelease](https://github.com/cloudfoundry-community/logsearch-boshrelease) with a fix [here](https://github.com/cloudfoundry-community/logsearch-boshrelease/pull/68) a while back and forgot to update here. Setting the 'redis.appendonly' parameter fixes it but also disables redis persistence.

This issue can be closed.
