### ISSUE TITLE
Understanding work with firehose-to-syslog and logsearch-for-cloudfoundry interaction

### ISSUE THREAD

**Issue by jhiemer** [cloudfoundry-community/logsearch-for-cloudfoundry#261]
Hey, 
I wanted to understand the behaviour of the filters (debugging purposes) with firehose-to-syslog. What I have done, is deployed firehose-to-syslog to CF as Go application and created a logstash instance with the following configuration
```ruby
input {
  tcp {
    port => 5000
    type => syslog
  }
  udp {
    port => 5000
    type => syslog
  }
}
filter {
...
}

output {
  stdout { codec => rubydebug }
}
```

So after starting the firehose-to-syslog I can see the following messages appearing in my rubydebug:

```ruby
{
    "@timestamp" => 2017-06-09T19:12:44.050Z,
          "port" => 54894,
      "@version" => "1",
          "host" => "217.26.224.12",
       "message" => "<6> 2017-06-09T19:12:44Z gpcm7tkkfbc doppler[14]: {\"cf_app_id\":\"c40cb3ad-87e3-49b1-ab94-914ef5698b43\",\"cf_app_name\":\"test-app\",\"cf_ignored_app\":false,\"cf_org_id\":\"ea268cca-1eb0-4295-b397-bb70716459d1\",\"cf_org_name\":\"demo\",\"cf_origin\":\"firehose\",\"cf_space_id\":\"cdce97f2-ede4-468b-b3f9-1ebef4e31484\",\"cf_space_name\":\"meetup\",\"deployment\":\"cf-ops-diego\",\"event_type\":\"LogMessage\",\"ip\":\"172.16.100.130\",\"job\":\"cell_z1\",\"job_index\":\"a1644c37-cab2-4e81-b011-d8d004737a36\",\"level\":\"info\",\"message_type\":\"OUT\",\"msg\":\"test-app. Says Hello. on index: 1\",\"origin\":\"rep\",\"source_instance\":\"1\",\"source_type\":\"APP/PROC/WEB\",\"time\":\"2017-06-09T19:12:44Z\",\"timestamp\":1497035564048554534}",
          "type" => "syslog"
}
```

Now the filters are not working because the following fields are not in the message:
* @message
* syslog_program

Could you help what I am missing?

**Comment by jhiemer** [comment]
Anyone? :-(

**Comment by hannayurkevich** [comment]
Hi @jhiemer, 

I'm not sure what filters do you use, but it looks like you are missing  [logsearch-boshrelease](https://github.com/cloudfoundry-community/logsearch-boshrelease) filters.

Field `@message` appears as result of rename in logsearch-boshrelease filters (see [here](https://github.com/cloudfoundry-community/logsearch-boshrelease/blob/develop/jobs/parser/templates/config/filters_pre.conf.erb#L39)). Field `syslog_program` is parsed in [syslog_standard.conf](https://github.com/cloudfoundry-community/logsearch-boshrelease/blob/develop/src/logsearch-config/src/logstash-filters/snippets/syslog_standard.conf#L4) snippet in logsearch-boshrelease.

So, logsearch-for-cloudfoundry relies on firehose-to-syslog message format but is also relies on loghsearch-boshrelease parsing. The fields you encountered problems with relate to logsearch-boshrelease parsing rules. So please make sure that you setup logsearch-for-cloudfoundry over logsearch-boshrelease correctly.

Thanks.

cc @Infra-Red

**Comment by jhiemer** [comment]
Hi @hannayurkevich,
thanks a lot for your response, really appreciate. Your answer helped me a lot to understand some basics. What I was searching for is essentially how I concatenate https://github.com/cloudfoundry-community/logsearch-boshrelease/blob/develop/src/logsearch-config/src/logstash-filters/snippets/syslog_standard.conf with https://github.com/cloudfoundry-community/logsearch-for-cloudfoundry/tree/develop/src/logsearch-config/src/logstash-filters/snippets to get some results. 

But if i see it correctly I have my syslog listener and then it is applied as follows:
* filters_pre
* syslog_standard
* app*

etc. What would be really helpful to understand and support debugging is how the filter rules are chained. This is the picture I am currently trying to build for me.

Thanks,
Johannes

**Comment by hannayurkevich** [comment]
@jhiemer,

Logsearch-boshrelease filters are aggregated into one config in this config - [parser_ctl](https://github.com/cloudfoundry-community/logsearch-boshrelease/blob/develop/jobs/parser/templates/bin/parser_ctl#L52-L82). From this file you can get the picture.

For logsearch-for-cloudfoundry filters you can see config [default.conf.erb](https://github.com/cloudfoundry-community/logsearch-for-cloudfoundry/blob/develop/src/logsearch-config/src/logstash-filters/default.conf.erb) to understand the filters ordering. You can also read this [doc](https://github.com/cloudfoundry-community/logsearch-for-cloudfoundry/blob/develop/docs/logs-parsing.md#parsing-rules) for more details. 

Let me know if you have any questions.

Hanna

**Comment by jhiemer** [comment]
@hannayurkevich thanks a lot for your support. I now got an understanding!

Johannes
