### ISSUE TITLE
bosh2 style deployment manifest needed.

### ISSUE THREAD

**Issue by kukgini** [cloudfoundry-community/logsearch-for-cloudfoundry#266]
I saw in logsearch-boshreleases project added bosh2 style deployment manifest.
Can you add for this Addon project too?

**Comment by Infra-Red** [comment]
Bosh2 deployment manifest in logsearch-boshrelease repo includes logsearch-for-cloudfoundry addon by default.

--
Regards,
Andrei

26 июля 2017 г., 12:54 +0300, kukgini <notifications@github.com>, писал:

**Comment by kukgini** [comment]
Oh. I got it. thank you.
