### ISSUE TITLE
User Needs to be in system ORG to view Logs when using UAA

### ISSUE THREAD

**Issue by henrys24** [cloudfoundry-community/logsearch-for-cloudfoundry#271]
Noticed that when using UAA a user needs to be in the system org to be able to view any Kibana Logs. Also they need to be added to every CF org that exist, if they need to view other application instance logs. IS there away to get logs for all orgs when using UAA

**Comment by Infra-Red** [comment]
Only users from administrators org/space able to see all logs in Kibana when UAA plugin is installed, you can specify any Cloud Foundry org as admin org during deployment with `kibana-auth.cloudfoundry.system_org` property.

--
Regards,
Andrei

23 авг. 2017 г., 13:48 +0300, henrys24 <notifications@github.com>, писал:
