### ISSUE TITLE
How to do the configuration to allow users except "admin" to access the Kibana portal?

### ISSUE THREAD

**Issue by maoyi8212** [cloudfoundry-community/logsearch-for-cloudfoundry#273]
Hi,
I have deployed the logsearch v206 and logsearch-for-cloudfoundry v204 in my cf environment. Now I plan to change the configuration to enable users(except admin) to access the kibana portal and they can only browser the applications which belong to the  authenrized orgs and spaces. Could you please give me some guide how to do that?

The readme mentioned that "Logsearch-for-cloudfoundry extends Kibana with authentication plugin. The plugin uses UAA (user authentication and authorization server for CloudFoundry) to authenticate a user and get the account information including organizations and spaces in CloudFoundry platform this user has rights to." Does that mean I need to create some new users by uaac? If it is true, what kinds of authorities I need to assign to them? 
Many thanks!

Regards,
Mao Yi

**Comment by Infra-Red** [comment]
Logsearch-for-cloudfoundry includes `create-uaa-client` errand which will create UAA client for Kinaba auth plugin.

--
Regards,
Andrei

31 авг. 2017 г., 13:51 +0200, maoyi <notifications@github.com>, писал:

**Comment by maoyi8212** [comment]
@Infra-Red Thank you for your reply.

I have deployed Kibana as CF application, and the `create-uaa-client` errand  also works for this deployment model. Right?

**Comment by maoyi8212** [comment]
And I checked the properties in the specification(the link below), could you please tell more specificly how to point the uaa client to a specific org and space? Many thanks!
https://github.com/cloudfoundry-community/logsearch-for-cloudfoundry/blob/914263b3c4576a98e7be785412892b00df43ea9b/jobs/create-uaa-client/spec
