### ISSUE TITLE
No Logs in Kibana. ES seems fine. 

### ISSUE THREAD

**Issue by stu-pete** [cloudfoundry-community/logsearch-for-cloudfoundry#275]
Hi,

I suspect I oversaw something but I'm not able to figure it out. 

Before I added logsearch-for-cf, Kibana showed logs for the platform itself just fine.
I chose to keep Kibana as a VM.

I deployed via tutorial and everything worked.

I can Log-In with CF credentials.

Checking Indexes on ES_Master

`curl es_master:9200/_aliases?pretty`
==>
`{
  ".kibana" : {
    "aliases" : { }
  },
  "logs-platform-2017.09.12" : {
    "aliases" : { }
  },
  "logs-app-2017.09.13" : {
    "aliases" : { }
  },
  "logs-platform-2017.09.13" : {
    "aliases" : { }
  }
}`

Searching on ES_Master

`curl 192.168.3.230:9200/logs-*/_search`
==> 
`{"took":13,"timed_out":false,"_shards":{"total":15,"successful":15,"failed":0},"hits":{"total":906952,"max_score":1.0, ............`

Kibana actually finds the FIELDs for the Index, but for some reason Discover it stays empty.

![grafik](https://user-images.githubusercontent.com/22984770/30373438-9fa5eab8-9881-11e7-9f1f-5e336fcca626.png)

![grafik](https://user-images.githubusercontent.com/22984770/30373257-f6e0a968-9880-11e7-983b-21b7c23fe6b9.png)

![grafik](https://user-images.githubusercontent.com/22984770/30373319-36ecdce8-9881-11e7-9e62-b1a3878fa7ce.png)

Kibana does actually search some pages:
![grafik](https://user-images.githubusercontent.com/22984770/30373950-659b390c-9883-11e7-92db-9d18753b8cd7.png)

But Results are always empty.
![grafik](https://user-images.githubusercontent.com/22984770/30373511-d782c7da-9881-11e7-9f12-6940cb0d9293.png)

I tried logging in with UAA_Admin (not client) for  logs-platform-* as well as a normal user assigned to an org for logs-app-*. 

Results stay empty

Further Info

`18619  done   Tue Sep 12 13:15:56 UTC 2017  Tue Sep 12 13:22:00 UTC 2017  director     logsearch                        create deployment`                                                    

`18634  done   Wed Sep 13 07:54:21 UTC 2017  Wed Sep 13 08:04:53 UTC 2017  director     logsearch                        run errand upload-kibana-objects from deployment logsearch`

**Comment by stu-pete** [comment]
I just checked the REDIS on Kibana VM and it gets populated with data as well. Here is the example key for admin:

`get kibana:sessions:cb5a3b10-9885-11e7-be4f-290fba18cabd
"{\"item\":{\"credentials\":{\"provider\":\"custom\",\"token\":\"<removed>\"},\"account\":{\"profile\":{\"displayName\":\" \",\"email\":\"admin\",\"raw\":{\"usely_name\":\"\",\"email\":\"admin\",\"phone_number\":null,\"name\":\" \"}},\"orgIds\":[\"78286b7-6b686c55ec8a\"],\"orgs\":[\"system\",\"development\",\"redis-smoke-test-org\"],\"space8-ba5e-4e00-b491-52a42737687e\",\"225ec62f-f85c-41e0-80f4-a9cec46ad1aa\",\"1d842302-155e-46edis-smoke-test-space\",\"melanie\"]}},\"stored\":1505308606895,\"ttl\":43200000}"`


Can you please point me in the right direction for further debugging? 

I understand that the kibana-auth-plugin edits the actual searches leaving kibana and limits them on basis of app_ids before they hit ES. But cannot seem to be able to find anything in the logs.

**Comment by Infra-Red** [comment]
@stu-pete Can you list the CF orgs which to which your user has access to and the value for the next property `kibana-auth.cloudfoundry.system_org`?
https://github.com/cloudfoundry-community/logsearch-for-cloudfoundry/blob/develop/jobs/kibana-auth-plugin/spec#L38-L40

**Comment by stu-pete** [comment]
Its the admin user. He has access to all orgs. 
 system
- development
- CF_SMOKE_TEST_ORG
- redis-smoke-test-org
(( two more orgs but i need names to be private so i rename them here.)) 
- org_a
- org_b

`cat config.sh` 
=>
`export USE_HTTPS="false"
export CF_API_URI="https://api.sys....."
export SKIP_SSL_VALIDATION="true"
export KIBANA_OAUTH2_CLIENT_ID="my_kibana_client_id"
export KIBANA_OAUTH2_CLIENT_SECRET="my_kibana_client_password"
export CF_SYSTEM_ORG="admin"
export SESSION_EXPIRATION_MS="43200000"
export REDIS_HOST="192.168.3.235"
export REDIS_PORT="6379"
export KIBANA_DOMAIN="10.41.88.251"`

Just checked and i did not set the property. it defaulted to "admin" in config.sh template from kibana-auth job. changed it to system for testing and it started working for the admin user..

`cat config.sh` 
=>
`export USE_HTTPS="false"
export CF_API_URI="https://api.sys....."
export SKIP_SSL_VALIDATION="true"
export KIBANA_OAUTH2_CLIENT_ID="my_kibana_client_id"
export KIBANA_OAUTH2_CLIENT_SECRET="my_kibana_client_password"
export CF_SYSTEM_ORG="system"
export SESSION_EXPIRATION_MS="43200000"
export REDIS_HOST="192.168.3.235"
export REDIS_PORT="6379"
export KIBANA_DOMAIN="10.41.88.251"`
so if i log in as cf uaa admin, I do see everything as expected! 

Now i tried logging in as a "normal user" with OrgManager for the Org, SpaceDev&SpaceManager authorization.
logs-plattform* => empty as expected
logs-apps* => empty as well :(

**Comment by janaurka** [comment]
I’m experience the same thing.

We have this the release up and running on PCF 1.11.x (dunno exactly which cf release that is) where it works fine. On a freshly installed PCF 1.12.x (again, dunno the exact cf release) I see the exact behaviour as @stu-pete is describing.

Maybe there was a change on how the logs are parsed in the `cf-release` (like in doppler or whatever?)


-----


Meh, sorry. That was a problem on our end. It appears to be working. Leaving the comment on the top to not confuse people. sorry :(

**Comment by stu-pete** [comment]
@janaurka would you be so kind and tell me what the error was? Maybe im doing the exact same thing :)

**Comment by janaurka** [comment]
@stu-pete : sure, i used a new bosh-director and i fcked up the ntp configuration (well, i simply left the default and port `123/udp` is not allowed to go outside in the network. So `ntp` failed and all the timestamps were wrong. So `kibana` actually had all the logs (in term of it could display it), *but* it only showed them asking for logs from the last `>=6 hours` because the time was ~6h behind on the vms deployed by bosh ;-)

**Comment by stu-pete** [comment]
yes, same here. fucked up ntp as well
