### ISSUE TITLE
could not be found in the datastructure

### ISSUE THREAD

**Issue by neppalli757** [cloudfoundry-community/logsearch-for-cloudfoundry#279]
Hello,
I am trying to deploy  Standalone Kibana with UAA OAuth enabled and i get this error while merging the manifests.  I downloaded the logsearch manifest which was deployed using boshv2 command, i used the below repository to deploy logsearch-boshrelease

https://github.com/cloudfoundry-community/logsearch-boshrelease/tree/develop/deployment

Error (Standalone Kibana with UAA OAuth enabled)
----------------
scripts/generate_deployment_manifest ~/deployment/logsearch_v1.yml templates/stub.logsearch-for-cf.standalone-kibana-with-auth.yml > ~/deployment/logsearch-with-logsearch-for-cf.yml
3 error(s) detected:
 - $.jobs.kibana.properties.kibana-auth.redis_host: Unable to resolve `jobs.kibana.networks.Deployment.static_ips.0`: `$.jobs.kibana.networks` could not be found in the datastructure
 - $.jobs.smoke-tests.properties.smoke_tests.elasticsearch_master.host: Unable to resolve `jobs.elasticsearch_master.networks.Deployment.static_ips.0`: `$.jobs.elasticsearch_master` could not be found in the datastructure
 - $.jobs.upload-kibana-objects.properties.elasticsearch.host: Unable to resolve `jobs.elasticsearch_master.networks.Deployment.static_ips.0`: `$.jobs.elasticsearch_master` could not be found in the datastructure

**Comment by Infra-Red** [comment]
Hi @neppalli757 . Could you please share `logsearch_v1.yml` and `stub.logsearch-for-cf.standalone-kibana-with-auth.yml` stubs. Please note that for v1 templates you should use the next templates: https://github.com/cloudfoundry-community/logsearch-boshrelease/tree/develop/templates.

**Comment by Infra-Red** [comment]
Hi @neppalli757. I'm going to close this issue due to inactivity, but feel free to open it if you need more help.
