### ISSUE TITLE
Allow Kibana to be hosted on a different domain than system_domain

### ISSUE THREAD

**Issue by aveyrenc** [cloudfoundry-community/logsearch-for-cloudfoundry#280]
Currently, we can't host Kibana on a domain other than the system_domain, because the system_domain is hard coded to generate the URL for Kibana logout redirection and UAA redirect URLs.

Is it possible to add a property allowing to specify an alternative domain for Kibana (and keep the system_domain to build the CF API URL) and fallback to the system_domain if not specified?

**Comment by srothwell01** [comment]
+1

Workaround is to modify the redirect URL of the UAA client
