### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by geofffranks** [cloudfoundry-community/logsearch-for-cloudfoundry#296]
Any plans for a new final release containing all the updates since the last one (august)? We have a dev release built from a while back, but it would be nice if we could use final releases + bosh.io instead

Really looking forward to being able to use the new stats server in the firehose-to-syslog ingestor

**Comment by axelaris** [comment]
Hi @Infra-Red,
do you have a bit of time to cut the new release?

**Comment by Infra-Red** [comment]
[v207](https://github.com/cloudfoundry-community/logsearch-for-cloudfoundry/releases/tag/v207.0.0) was released.
