### ISSUE TITLE
Version mismatch in cf-kibana package

### ISSUE THREAD

**Issue by amhuber** [cloudfoundry-community/logsearch-for-cloudfoundry#308]
When trying to compile cf-kibana this error is being thrown:

    Error: Action Failed get_task: Task 2a8c232d-d25d-4297-4c4b-9b535ceae962 result: Compiling package cf-kibana: Running packaging script: Running packaging script: Command exited with 70; Stdout: Transferring 3845175 bytes....................
    Transfer complete
    Retrieving metadata from plugin archive
    Extracting plugin archive
    Extraction complete
    , Stderr: + tar xzf cf-kibana/kibana-5.6.4-linux-x86_64.tar.gz --strip 1 -C /var/vcap/packages/cf-kibana
    + cd /var/vcap/packages/cf-kibana
    + bin/kibana-plugin install file:///var/vcap/packages/kibana-auth-plugin/kibana-auth-plugin.zip
    Plugin installation was unsuccessful due to error "Incorrect Kibana version in plugin [authentication]. Expected [5.6.4]; found [5.6.13]"

**Comment by Infra-Red** [comment]
Hi @amhuber ! Thanks for reporting the issue, I will update `cf-kibana` package and publish a new release for logsearch-for-cloudfoundry.

**Comment by amhuber** [comment]
Thanks, I'm able to compile the package now using the new final release.
