### ISSUE TITLE
how can i block platform logs to shipped from cf to elasticsearch?

### ISSUE THREAD

**Issue by ghost** [cloudfoundry-community/logsearch-for-cloudfoundry#313]
I need only the app logs to be visible on my kibana dashboard.
I tried to block the port 5514 in Security Group , but that didn't helped .
can someone guide me on this  ?

**Comment by Infra-Red** [comment]
Hi @lordcf !
What you use to send platform logs from Cloud Foundry VMs to Logsearch? 
Usually we prefer to deploy [syslog-release](https://github.com/cloudfoundry/syslog-release) as [BOSH runtime config](https://bosh.io/docs/runtime-config/) to configure platform logs forwarding. If this is the case, then you just need to remove syslog configuration.

**Comment by ghost** [comment]
hi @Infra-Red , 
Thank you for your response .
I am use basic cf-deployment version 1.17, in which syslog-release is not used then too i am getting platform logs . Is there any other way in which logs are shipped?
If yes the please guide me , I am a new bee to ELK.

**Comment by Infra-Red** [comment]
@lordcf Please check CF deployment manifest and BOSH runtime config for `syslog_forwarder` job.
```sh
bosh -d <CF-DEPLOYMENT-NAME> manifest | grep syslog_forwarder
bosh runtime-config | grep syslog_forwarder
```

**Comment by ghost** [comment]
@Infra-Red  I just have syslog_drain in my manifest .
syslog_forwarder is present in an operations addons file , but i am not using that addons yet.

**Comment by ghost** [comment]
now I am using syslog-forwarded release with cf-deployment v1.17 , but i am not using nats-to-syslog jobs in ELK .
and I am not getting platform logs .
Is is so that platform logs require nats-to-syslog job ?

**Comment by Infra-Red** [comment]
@lordcf No, `nats-to-syslog` job is not required for this. Could you please list all indexes in Elasticsearch:
```sh
curl '<ELASTICSEARCH-IP>:9200/_cat/indices?v'
```

**Comment by ghost** [comment]
@Infra-Red 
yes , 2 indices get created namely:
logs-platform-2019-02-04
logs-app-2019-02-04
but when i see these indices in kibana , in logs-app-* i can see logs of all the apps , 
and in logs-platform-* i can see only one log which is of the smoke-test errand that i ran after deploying ELK
