### ISSUE TITLE
upload-kibana-objects does not work with Kibana v6

### ISSUE THREAD

**Issue by vetin4ri** [cloudfoundry-community/logsearch-for-cloudfoundry#318]
Hi,

I have seen the know issues note in releases tab, but is there any bug report tracking the issue?

Additionally, is there any more specific information about what has to be changed? I have seen the info: https://www.elastic.co/guide/en/elasticsearch/reference/6.7/removal-of-types.html, but I don't really see why it affects all imported objects as documents seem to be added to the without an error to ".kibana" index and there is only one type ("doc") in the json?

**Comment by Infra-Red** [comment]
Hi @vetin4ri ! Current implementation of `upload-kibana-object` errand tries to post all documents to `.kibana` index. Kibana v6 introduces [Saved Objects API](https://www.elastic.co/guide/en/kibana/6.3/saved-objects-api.html) which should be used for such operations. Also documents format was changed a bit. I will try to work on errand issue this week, but I don't have exact timelines when this issue will be fixed.

**Comment by vetin4ri** [comment]
Thanks, let me know if you need any help with that!
