### ISSUE TITLE
upload-kibana-objects fails on the first run

### ISSUE THREAD

**Issue by pritesh-patel95** [cloudfoundry-community/logsearch-for-cloudfoundry#329]
Running a concourse pipeline in the following order: bosh-deploy > create-uaa-user-errand > smoke-tests-errand > upload-kibana-objects errand

The `upload-kibana-objects` errand fails every time with the following error:

```
File "/var/vcap/jobs/upload-kibana-objects/bin/import-objects", line 16, in <module>  
Upload Kibana objects from job defaults. Start processing...                                                                              
assert logs.url == 'https://login.((OUR_SYSTEM_DOMAIN))/login'     
AssertionError  
```

The errand runs successfully when run a second time - i.e., via BOSH cli or re-running the pipeline.

**Comment by TheMoves** [comment]
I had to log in manually as CF Admin ID into Kibana to allow the upload-kibana-objects to actually succeed

**Comment by axelaris** [comment]
It can be resolved to setting this value to `true`: https://github.com/cloudfoundry-community/logsearch-for-cloudfoundry/blob/develop/jobs/create-uaa-client/spec#L26
