### ISSUE TITLE
upload-kibana-objects fails when using domain names other than `logs` and `login`

### ISSUE THREAD

**Issue by bengerman13** [cloudfoundry-community/logsearch-for-cloudfoundry#331]
running the upload-kibana-objects job fails with this error on our system, where we're using urls other than `logs.$SYSTEM_DOMAIN` and `login.$SYSTEM_DOMAIN`

```
Stderr     Traceback (most recent call last):  
             File "/var/vcap/jobs/upload-kibana-objects/bin/import-objects", line 16, in <module>  
               assert logs.url == <our login url>  
           AssertionError  
```
that's happening [here](https://github.com/cloudfoundry-community/logsearch-for-cloudfoundry/blob/develop/jobs/upload-kibana-objects/templates/bin/import-objects#L23).

I'm happy to do the work to make this variable (with the current expected values as defaults, of course) but I want to make sure I'm not off-base here first.

**Comment by bengerman13** [comment]
I looked further at this, and it's worse for us than I thought - this successfully uploaded objects to the wrong instance (we have 2 logsearch instances in each environment with different configs and urls)

**Comment by axelaris** [comment]
Should be resolved by https://github.com/cloudfoundry-community/logsearch-for-cloudfoundry/pull/336
