### ISSUE TITLE
Only 50 spaces per user

### ISSUE THREAD

**Issue by bengerman13** [cloudfoundry-community/logsearch-for-cloudfoundry#338]
The kibana-auth-plugin only caches 50 spaces per user, so if a user has roles in more than 50 spaces, they will not be able to view logs in all their spaces.

**Comment by axelaris** [comment]
PR is closed

**Comment by bengerman13** [comment]
@axelaris FWIW - the PR was closed because I tested more and the fix didn't work, but this issue still exists.

We're tracking and trying to fix ourselves, so feel free to leave this closed if it's not useful to others.
