### ISSUE TITLE
Upgrade to Kibana 7.X (or at least 6.8.6)

### ISSUE THREAD

**Issue by pburkholder** [cloudfoundry-community/logsearch-for-cloudfoundry#340]
We'd like some findings on Content-Security-Policy to go away, so upgrading to 7.X would take care of that.

Thanks, Peter

**Comment by axelaris** [comment]
It almost there: https://github.com/cloudfoundry-community/logsearch-boshrelease/tree/v7
Any tests/feedback are welcome!

**Comment by axelaris** [comment]
Done: https://github.com/cloudfoundry-community/logsearch-for-cloudfoundry/commit/1eab92216c3c9b316335f7ca2841dccc14c75af0

**Comment by pburkholder** [comment]
@axelaris Terrific! Thanks so much. If you don't hear from me, it means it's all gone well!
