### ISSUE TITLE
RTR logs always contain the `router/parsing_failed` tag even when parsed successfully

### ISSUE THREAD

**Issue by mymasse** [cloudfoundry-community/logsearch-for-cloudfoundry#344]
Whenever RTR logs are parsed they always contain the tag `router/parsing_failed`.

Looking at the code it looks like that tag is added in the `platform-gorouter.conf` snippet, however these logs would have already been parsed by `app-logmessage-rtr.conf` snippet loaded before.

Should the `platform-gorouter.conf` include some other check than just `[@source][component] == "gorouter"` which is true in both app and platform logs?

**Comment by axelaris** [comment]
Fixed by https://github.com/cloudfoundry-community/logsearch-for-cloudfoundry/commit/51681be68c287375772c22ad86bbb21d90c53c6f
