### ISSUE TITLE
logsearch-smoke-tests submodules points to an unknown commit

### ISSUE THREAD

**Issue by mymasse** [cloudfoundry-community/logsearch-for-cloudfoundry#347]
When cloning the repo and initializing the submodules it fails for the `logsearch-smoke-tests` since the commit doesn't exist.

https://github.com/cloudfoundry-community/logsearch-smoke-tests/tree/ae4c01c4fdd80a846e619f7b7757ee8bff5b189a

**Comment by axelaris** [comment]
Fixed
