### ISSUE TITLE
Non-standard property label format

### ISSUE THREAD

**Issue by drnic** [cloudfoundry-community/logsearch-for-cloudfoundry#46]
bosh upload release https://logsearch-for-cloudfoundry-boshrelease.s3.amazonaws.com/boshrelease-logsearch-for-cloudfoundry-4.tgz

Can we switch to lower case, underscore for manifest properties to be consistent across all releases?

**Comment by hannayurkevich** [comment]
Closing the issue because it looks obsolete.
