### ISSUE TITLE
./bin/test fails

### ISSUE THREAD

**Issue by yatzek** [cloudfoundry-community/logsearch-for-cloudfoundry#51]
Using oracle jdk1.8.0_45 on ubuntu 14.04:

./bin/test 
mkdir -p target
rm -rf target/*
===> Building ...
cp src/kibana4-dashboards/kibana.json target/kibana4-dashboards.json
===> Artifacts:
target
├── kibana4-dashboards.json
└── logstash-filters-default.conf

0 directories, 2 files
===> Testing ...
 JAVA_OPTS="$JAVA_OPTS -XX:+TieredCompilation -XX:TieredStopAtLevel=1" vendor/logstash/bin/logstash rspec $(find test -name *spec.rb) 
Using Accessor#strict_set for specs
Run options: exclude {:redis=>true, :socket=>true, :performance=>true, :couchdb=>true, :elasticsearch=>true, :elasticsearch_secure=>true, :broken=>true, :export_cypher=>true, :integration=>true, :windows=>true}
........F.....F..

Failures:

  1) LogStash::Filters::Grok Parse Cloud Foundry doppler messages Decorate app logs with name, org and space "{"@type":"syslog","@message":"<6>2015-03-17T01:22:4..." when processed
     Failure/Error: Unable to find matching line from backtrace
     Insist::Failure:
       Expected "myappname", but got nil
     # ./test/logstash-filters/snippets/doppler-spec.rb:144:in `(root)'
     # ./vendor/logstash/lib/logstash/runner.rb:22:in `run'
     # ./vendor/logstash/lib/logstash/runner.rb:71:in `run'
     # ./vendor/logstash/lib/logstash/runner.rb:129:in `run'

  2) LogStash::Filters::Grok Ensure non-NATS messages are ignored "{"@type":"relp","host":"1.2.3.4","@message":"<78>Ap..." when processed
     Failure/Error: Unable to find matching line from backtrace
     Insist::Failure:
       Expected ["syslog_standard"], but got ["syslog_standard", "_grokparsefailure-cf-vcap"]
     # ./test/logstash-filters/snippets/vcap-spec.rb:73:in `(root)'
     # ./vendor/logstash/lib/logstash/runner.rb:22:in `run'
     # ./vendor/logstash/lib/logstash/runner.rb:71:in `run'
     # ./vendor/logstash/lib/logstash/runner.rb:129:in `run'

Finished in 13.94 seconds
17 examples, 2 failures

Failed examples:

rspec ./vendor/logstash/vendor/bundle/jruby/1.9/gems/logstash-devutils-0.0.10-java/lib/logstash/devutils/rspec/logstash_helpers.rb:51 # LogStash::Filters::Grok Parse Cloud Foundry doppler messages Decorate app logs with name, org and space "{"@type":"syslog","@message":"<6>2015-03-17T01:22:4..." when processed
rspec ./vendor/logstash/vendor/bundle/jruby/1.9/gems/logstash-devutils-0.0.10-java/lib/logstash/devutils/rspec/logstash_helpers.rb:51 # LogStash::Filters::Grok Ensure non-NATS messages are ignored "{"@type":"relp","host":"1.2.3.4","@message":"<78>Ap..." when processed

Randomized with seed 50154

rake aborted!
Command failed with status (1): [ JAVA_OPTS="$JAVA_OPTS -XX:+TieredCompilat...]
/home/jacek/workspace/logsearch-for-cloudfoundry/Rakefile:23:in `block in <top (required)>'
Tasks: TOP => test
(See full trace by running task with --trace)

Any ideas?

**Comment by yatzek** [comment]
Same results when run inside vagrant logsearch workspace:

[logsearch workspace] ~/src/logsearch-for-cloudfoundry ▸ git status
HEAD detached at v4
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   target/logstash-filters-default.conf

no changes added to commit (use "git add" and/or "git commit -a")
[logsearch workspace] ~/src/logsearch-for-cloudfoundry ▸ git checkout target/logstash-filters-default.conf
[logsearch workspace] ~/src/logsearch-for-cloudfoundry ▸ git status
HEAD detached at v4
nothing to commit, working directory clean
[logsearch workspace] ~/src/logsearch-for-cloudfoundry ▸ ./bin/test 
mkdir -p target
rm -rf target/*
===> Building ...
cp src/kibana4-dashboards/kibana.json target/kibana4-dashboards.json
===> Artifacts:
target
├── kibana4-dashboards.json
└── logstash-filters-default.conf

0 directories, 2 files
===> Testing ...
 JAVA_OPTS="$JAVA_OPTS -XX:+TieredCompilation -XX:TieredStopAtLevel=1" vendor/logstash/bin/logstash rspec $(find test -name *spec.rb) 
Using Accessor#strict_set for specs
Run options: exclude {:redis=>true, :socket=>true, :performance=>true, :couchdb=>true, :elasticsearch=>true, :elasticsearch_secure=>true, :broken=>true, :export_cypher=>true, :integration=>true, :windows=>true}
..F............F.

Failures:

  1) LogStash::Filters::Grok Parse Cloud Foundry doppler messages Decorate app logs with name, org and space "{"@type":"syslog","@message":"<6>2015-03-17T01:22:4..." when processed
     Failure/Error: Unable to find matching line from backtrace
     Insist::Failure:
       Expected "myappname", but got nil
     # ./test/logstash-filters/snippets/doppler-spec.rb:144:in `(root)'
     # ./vendor/logstash/lib/logstash/runner.rb:22:in `run'
     # ./vendor/logstash/lib/logstash/runner.rb:71:in `run'
     # ./vendor/logstash/lib/logstash/runner.rb:129:in `run'

  2) LogStash::Filters::Grok Ensure non-NATS messages are ignored "{"@type":"relp","host":"1.2.3.4","@message":"<78>Ap..." when processed
     Failure/Error: Unable to find matching line from backtrace
     Insist::Failure:
       Expected ["syslog_standard"], but got ["syslog_standard", "_grokparsefailure-cf-vcap"]
     # ./test/logstash-filters/snippets/vcap-spec.rb:73:in `(root)'
     # ./vendor/logstash/lib/logstash/runner.rb:22:in `run'
     # ./vendor/logstash/lib/logstash/runner.rb:71:in `run'
     # ./vendor/logstash/lib/logstash/runner.rb:129:in `run'

Finished in 18.53 seconds
17 examples, 2 failures

Failed examples:

rspec ./vendor/logstash/vendor/bundle/jruby/1.9/gems/logstash-devutils-0.0.10-java/lib/logstash/devutils/rspec/logstash_helpers.rb:51 # LogStash::Filters::Grok Parse Cloud Foundry doppler messages Decorate app logs with name, org and space "{"@type":"syslog","@message":"<6>2015-03-17T01:22:4..." when processed
rspec ./vendor/logstash/vendor/bundle/jruby/1.9/gems/logstash-devutils-0.0.10-java/lib/logstash/devutils/rspec/logstash_helpers.rb:51 # LogStash::Filters::Grok Ensure non-NATS messages are ignored "{"@type":"relp","host":"1.2.3.4","@message":"<78>Ap..." when processed

Randomized with seed 47767

rake aborted!
Command failed with status (1): [ JAVA_OPTS="$JAVA_OPTS -XX:+TieredCompilat...]
/home/vagrant/src/logsearch-for-cloudfoundry/Rakefile:23:in `block in <top (required)>'
Tasks: TOP => test
(See full trace by running task with --trace)
[logsearch workspace] ~/src/logsearch-for-cloudfoundry ▸ java -version
java version "1.7.0_79"
OpenJDK Runtime Environment (IcedTea 2.5.5) (7u79-2.5.5-0ubuntu0.14.04.2)

**Comment by Infra-Red** [comment]
Tests failing fix was introduced in next PR https://github.com/cloudfoundry-community/logsearch-for-cloudfoundry/pull/123. 
@axelaris We can close this issue.

**Comment by axelaris** [comment]
Agree, thanks @Infra-Red
