### ISSUE TITLE
Package name collision detected in job (upgrade from v3 to v6)

### ISSUE THREAD

**Issue by datianshi** [cloudfoundry-community/logsearch-for-cloudfoundry#63]
I used to have an ingestor job that has firehose, syslog and relp all together
But when upgraded to v6
I got 
Started preparing deployment > Binding templates. Failed: Package name collision detected in job `ingestor': template `logsearch-for-cloudfoundry/ingestor_cloudfoundry-firehose' depends on package `logsearch-for-cloudfoundry/logstash', template `logsearch/ingestor_relp' depends on `logsearch/logstash'. BOSH cannot currently collocate two packages with identical names from separate releases. (00:00:00)

The reason is since v4, the logsearch-for-cloudfoundry include a package named as logstash. Now I have to split them into two separate VMs.

- instances: 1
  name: ingestor
  networks:
  - name: ls1
    static_ips:
    - xxxxxxx
  release: logsearch
  resource_pool: common
  templates:
  - name: ingestor_cloudfoundry-firehose
    release: logsearch-for-cloudfoundry
  - name: ingestor_syslog
  - name: ingestor_relp

**Comment by shinji62** [comment]
Related to https://github.com/logsearch/logsearch-for-cloudfoundry/issues/45 no ?
