### ISSUE TITLE
Not all vcap messages are JSON

### ISSUE THREAD

**Issue by dpb587** [cloudfoundry-community/logsearch-for-cloudfoundry#7]
For example... the following [document](http://api.meta.logsearch.io/logstash-2014.06.05/relp_cf/YTLKANrZQeqSY2JDFEdaTw?pretty) does not have JSON data. We should probably do a JSON check similar to loggregator.

    {
        "@version": "1",
        "@timestamp": "2014-06-05T20:13:02.956+00:00",
        "_logstash_input": "relp",
        "host": "192.0.2.14:40625",
        "@type": "relp_cf",
        "@message": "<14>2014-06-05T20:13:02.956408+00:00 192.0.2.15 vcap.cloud_controller_ng.stdout [job=vcap.cloud_controller_ng.stdout index=0]  192.0.2.16, 192.0.2.17, 192.0.2.18 - - [05/Jun/2014 20:13:02] \"GET /info HTTP/1.0\" 200 283 0.0030",
        "syslog_pri": "14",
        "received_at": "2014-06-05 20:12:19 +0000",
        "received_from": "192.0.2.14:40625",
        "tags": [
          "syslog_standard",
          "_jsonparsefailure",
          "cloudfoundry_vcap"
        ],
        "@source.host": "192.0.2.15",
        "@job.name": "vcap_cloud_controller_ng_stdout",
        "@job.index": "0",
        "_message_json": " 192.0.2.16, 192.0.2.17, 192.0.2.18 - - [05/Jun/2014 20:13:02] \"GET /info HTTP/1.0\" 200 283 0.0030",
        "@shipper.name": "vcap_cloud_controller_ng_stdout_relp",
        "@job.host": "192.0.2.15",
        "@shipper.priority": "14"
    }

**Comment by keymon** [comment]
In this other project, we solved the issue with these commits in our copy of the filters:
 * https://github.com/alphagov/cf-terraform/commit/6129380e4a8c1b243033c45acdbc90643ccb182a
 * https://github.com/alphagov/cf-terraform/commit/41d0160dec279bc4b69b3841693c5ad81950bf00

We need to do a proper PR on this repo, but work needs to be prioritised.

**Comment by hannayurkevich** [comment]
This is not an issue anymore, because vcap.conf now checks for message format before parsing it with json filter. See https://github.com/cloudfoundry-community/logsearch-for-cloudfoundry/blob/master/src/logsearch-config/src/logstash-filters/snippets/vcap.conf#L7.

**Comment by axelaris** [comment]
Ok, closing
