### ISSUE TITLE
Remove bundled logstash from ingestor_cloudfoundry-firehose job

### ISSUE THREAD

**Issue by mrdavidlaing** [cloudfoundry-community/logsearch-for-cloudfoundry#80]

**Comment by vfonsecapv** [comment]
There some problem with ingestor_cloudfoundry-firehose. Do you what is?

**Comment by mrdavidlaing** [comment]
@vfonsecapv - Please can you provide some more details on what your issue is.

**Comment by vfonsecapv** [comment]
When I realize the deployment, creating the release (bosh bosh create release and release upload) the job in question does not work.

I checked in monit summary and the one who does not start is ingestor_cloudfoundry-firehose

We have some specific problem with it?

**Comment by vfonsecapv** [comment]
monit summary:

Process 'ingestor_cloudfoundry-firehose' not monitored

monit start ingestor_cloudfoundry-firehose

Process 'ingestor_cloudfoundry-firehose' Execution failed - start pending

syslog erros:
`
{:timestamp=>"2016-05-09T12:42:31.323000+0000", :message=>"SIGTERM received. Shutting down the pipeline.", :level=>:warn}
{:timestamp=>"2016-05-09T12:42:31.472000+0000", :message=>"UDP listener died", :exception=>#<IOError: closed stream>, :backtrace=>["org/jruby/RubyIO.java:3682:in `select'", "/var/vcap/packages/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-udp-2.0.5/lib/logstash/inputs/udp.rb:77:in `udp_listener'", "/var/vcap/packages/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-udp-2.0.5/lib/logstash/inputs/udp.rb:50:in `run'", "/var/vcap/packages/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.2.3-java/lib/logstash/pipeline.rb:331:in `inputworker'", "/var/vcap/packages/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.2.3-java/lib/logstash/pipeline.rb:325:in `start_input'"], :level=>:warn}
`
-----
`
$PATH /var/vcap/packages/logstash/bin:/var/vcap/packages/java8/bin:/var/vcap/packages/firehose-to-syslog/bin:/bin:/usr/bin:/sbin:/usr/sbin
Starting CF firehose-to-syslog ingestor...
Disabling IPv6...
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
net.ipv6.conf.lo.disable_ipv6 = 1
Waiting 1m for syslog ingestor to accept connections...
nc: getaddrinfo: Name or service not known
Waiting for syslog to accept connections (1 of 12)...
nc: getaddrinfo: Name or service not known
Waiting for syslog to accept connections (2 of 12)...
nc: getaddrinfo: Name or service not known
Waiting for syslog to accept connections (3 of 12)...
nc: getaddrinfo: Name or service not known
Waiting for syslog to accept connections (4 of 12)...
nc: getaddrinfo: Name or service not known
Waiting for syslog to accept connections (5 of 12)...
nc: getaddrinfo: Name or service not known
Waiting for syslog to accept connections (6 of 12)...
$PATH /var/vcap/packages/logstash/bin:/var/vcap/packages/java8/bin:/var/vcap/packages/firehose-to-syslog/bin:/bin:/usr/bin:/sbin:/usr/sbin
`

**Comment by axelaris** [comment]
Obsoleted
