### ISSUE TITLE
Refer related breaking issue from logsearch-boshworkspace repo

### ISSUE THREAD

**Issue by emirozer** [cloudfoundry-community/logsearch-for-cloudfoundry#83]
https://github.com/cloudfoundry-community/logsearch-boshworkspace/issues/19

**Comment by emirozer** [comment]
There is no "logsearch-for-cloudfoundry-boshrelease" directory.

**Comment by Infra-Red** [comment]
[cloudfoundry-community/logsearch-boshworkspace](https://github.com/cloudfoundry-community/logsearch-boshworkspace) is outdated. Close issue as obsolete.
