### ISSUE TITLE
Support multiple logsearch deployments 

### ISSUE THREAD

**Issue by anklei** [cloudfoundry-community/logsearch-for-cloudfoundry#97]
Hi,
we are trying to stream cf logs to multiple logsearch deployments with different configurations. For that we need to set a custom firehose_subscription_id. Does it make sense to add this option to logseach-for-cloudfoundry release?

**Comment by cromega** [comment]
@anklei: It certainly does. Currently the subscription ID is not configurable. If you make the change to the release we will review and merge it.

**Comment by anklei** [comment]
thanks for the feedback, here is the pull request: https://github.com/cloudfoundry-community/logsearch-for-cloudfoundry/pull/98

**Comment by anklei** [comment]
any chance you can have a look at my pull request in the near future?

**Comment by Infra-Red** [comment]
Fixed in 8cdb1c11d8483f2b62ef709b8b5d4e2f239c0203 .
