### ISSUE TITLE
create release fails

### ISSUE THREAD

**Issue by tomsherrod** [cloudfoundry-community/logsearch-for-cloudfoundry#99]
Cloning down, running "bosh create release" resulted in "Package 'collector' has a glob that resolves to an empty file list: collector/{Rakefile,Gemfile,Gemfile.lock}"

Ran an update, "bosh create release" got further and resulted in "Package 'logsearch-for-cloudfoundry-filters' has a glob that resolves to an empty file list: logsearch-config/target/logstash-filters-default.conf" I don't see this in the repo.

What did I miss?

**Comment by cromega** [comment]
@tomsherrod 

1, collector: run `git submodule init && git submodule update` or clone with the `--recursive` flag
2, missing logstash-filter-default.conf: run `src/logsearch-config/bin/build`. Thanks for pointing out some missing bits in the documentation.

**Comment by tomsherrod** [comment]
Success! Many thanks.
Now to see what can be done with it!
